/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd.RewardContentUI;

/**
 *
 * @author admin
 */
public class RewardEmployeeContentPanel extends javax.swing.JFrame {

    /**
     * Creates new form RewardEmployeeContentPanel
     */
    public RewardEmployeeContentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rewardEmployeeFormContainer = new javax.swing.JPanel();
        RewardEmployeeLabel = new javax.swing.JLabel();
        RewardEmployeeForm = new javax.swing.JPanel();
        RewardIDLabel = new javax.swing.JLabel();
        RewardIDTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        RewardNameLabel = new javax.swing.JLabel();
        RewardNameTextField = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        rewardNumLabel = new javax.swing.JLabel();
        RewardNumTextField = new javax.swing.JTextField();
        typeRewardNameLabel1 = new javax.swing.JLabel();
        EmployeeComboBox = new javax.swing.JComboBox<>();
        RewardNameEmployeeLabel = new javax.swing.JLabel();
        typeRewardComboBox = new javax.swing.JComboBox<>();
        moneyLabel = new javax.swing.JLabel();
        moneySpinner = new javax.swing.JSpinner();
        rewardEmployeeTableContainer = new javax.swing.JPanel();
        RewardEmployeeTableLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RewardEmployeeTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1055, 640));

        rewardEmployeeFormContainer.setBackground(new java.awt.Color(255, 255, 255));
        rewardEmployeeFormContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rewardEmployeeFormContainer.setName("rewardEmployeeFormContainer"); // NOI18N

        RewardEmployeeLabel.setBackground(new java.awt.Color(255, 255, 255));
        RewardEmployeeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RewardEmployeeLabel.setText("Tạo Khen Thưởng");
        RewardEmployeeLabel.setName("RewardEmployeeLabel"); // NOI18N
        RewardEmployeeLabel.setOpaque(true);

        RewardEmployeeForm.setBackground(new java.awt.Color(255, 255, 255));
        RewardEmployeeForm.setName("RewardEmployeeForm"); // NOI18N

        RewardIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RewardIDLabel.setText("Mã Khen Thưởng:");
        RewardIDLabel.setName("RewardIDLabel"); // NOI18N

        RewardIDTextField.setBackground(new java.awt.Color(204, 204, 204));
        RewardIDTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RewardIDTextField.setEnabled(false);
        RewardIDTextField.setName("RewardIDTextField"); // NOI18N
        RewardIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RewardIDTextFieldActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(25, 135, 84));
        addButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addButton.setText("Thêm");
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addButton.setIconTextGap(10);
        addButton.setName("addButton"); // NOI18N

        deleteButton.setBackground(new java.awt.Color(220, 53, 69));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        deleteButton.setText("Xóa");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.setIconTextGap(10);
        deleteButton.setName("deleteButton"); // NOI18N
        deleteButton.setOpaque(true);

        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        updateButton.setText("Sửa");
        updateButton.setIconTextGap(10);
        updateButton.setName("updateButton"); // NOI18N
        updateButton.setOpaque(true);

        RewardNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RewardNameLabel.setText("Tên Khen Thưởng :");
        RewardNameLabel.setName("RewardNameLabel"); // NOI18N

        RewardNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        RewardNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RewardNameTextField.setName("RewardNameTextField"); // NOI18N
        RewardNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RewardNameTextFieldActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(108, 117, 125));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Hủy Bỏ");
        cancelBtn.setName("cancelBtn"); // NOI18N

        rewardNumLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rewardNumLabel.setText("Số Quyết Định :");
        rewardNumLabel.setName("typeRewardNameLabel"); // NOI18N

        RewardNumTextField.setBackground(new java.awt.Color(204, 204, 204));
        RewardNumTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RewardNumTextField.setName("typeRewardNameTextField"); // NOI18N

        typeRewardNameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        typeRewardNameLabel1.setText("Chọn Loại Khen Thưởng:");
        typeRewardNameLabel1.setName("typeRewardNameLabel"); // NOI18N

        EmployeeComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmployeeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RewardNameEmployeeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RewardNameEmployeeLabel.setText("Chọn Nhân Viên");
        RewardNameEmployeeLabel.setName("typeRewardNameLabel"); // NOI18N

        typeRewardComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        typeRewardComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeRewardComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeRewardComboBoxActionPerformed(evt);
            }
        });

        moneyLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        moneyLabel.setText("Số Tiền Thưởng:");

        moneySpinner.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout RewardEmployeeFormLayout = new javax.swing.GroupLayout(RewardEmployeeForm);
        RewardEmployeeForm.setLayout(RewardEmployeeFormLayout);
        RewardEmployeeFormLayout.setHorizontalGroup(
            RewardEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RewardEmployeeFormLayout.createSequentialGroup()
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(RewardEmployeeFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RewardEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RewardEmployeeFormLayout.createSequentialGroup()
                        .addGroup(RewardEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeRewardNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmployeeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typeRewardComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(RewardEmployeeFormLayout.createSequentialGroup()
                                .addComponent(moneyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moneySpinner))
                            .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RewardNameEmployeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RewardEmployeeFormLayout.createSequentialGroup()
                        .addGroup(RewardEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RewardNumTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RewardEmployeeFormLayout.createSequentialGroup()
                                .addGroup(RewardEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rewardNumLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RewardNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RewardIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RewardEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RewardIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(RewardNameTextField))))
                        .addGap(29, 29, 29))))
        );
        RewardEmployeeFormLayout.setVerticalGroup(
            RewardEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RewardEmployeeFormLayout.createSequentialGroup()
                .addGroup(RewardEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RewardIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RewardIDTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RewardEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RewardEmployeeFormLayout.createSequentialGroup()
                        .addComponent(RewardNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rewardNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RewardNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RewardNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RewardNameEmployeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeRewardNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeRewardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RewardEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyLabel))
                .addGap(18, 18, 18)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RewardEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rewardEmployeeFormContainerLayout = new javax.swing.GroupLayout(rewardEmployeeFormContainer);
        rewardEmployeeFormContainer.setLayout(rewardEmployeeFormContainerLayout);
        rewardEmployeeFormContainerLayout.setHorizontalGroup(
            rewardEmployeeFormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rewardEmployeeFormContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rewardEmployeeFormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RewardEmployeeForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RewardEmployeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        rewardEmployeeFormContainerLayout.setVerticalGroup(
            rewardEmployeeFormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rewardEmployeeFormContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RewardEmployeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RewardEmployeeForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rewardEmployeeTableContainer.setBackground(new java.awt.Color(255, 255, 255));
        rewardEmployeeTableContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rewardEmployeeTableContainer.setName("rewardEmployeeTableContainer"); // NOI18N

        RewardEmployeeTableLabel.setBackground(new java.awt.Color(255, 255, 255));
        RewardEmployeeTableLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RewardEmployeeTableLabel.setText("Khen Thưởng Nhân Viên");
        RewardEmployeeTableLabel.setName("RewardEmployeeTableLabel"); // NOI18N
        RewardEmployeeTableLabel.setOpaque(true);

        RewardEmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Khen Thưởng", "Tên Khen Thưởng", "Tên Nhân Viên", "Mã Loại Khen Thưởng", "Số Quyết Định", "Số Tiền", "Ngày Tạo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RewardEmployeeTable.setName("degreeTable"); // NOI18N
        RewardEmployeeTable.setRowHeight(40);
        jScrollPane1.setViewportView(RewardEmployeeTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rewardEmployeeTableContainerLayout = new javax.swing.GroupLayout(rewardEmployeeTableContainer);
        rewardEmployeeTableContainer.setLayout(rewardEmployeeTableContainerLayout);
        rewardEmployeeTableContainerLayout.setHorizontalGroup(
            rewardEmployeeTableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rewardEmployeeTableContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rewardEmployeeTableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RewardEmployeeTableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        rewardEmployeeTableContainerLayout.setVerticalGroup(
            rewardEmployeeTableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rewardEmployeeTableContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RewardEmployeeTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(rewardEmployeeFormContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rewardEmployeeTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rewardEmployeeFormContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rewardEmployeeTableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RewardIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RewardIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RewardIDTextFieldActionPerformed

    private void RewardNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RewardNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RewardNameTextFieldActionPerformed

    private void typeRewardComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeRewardComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeRewardComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RewardEmployeeContentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RewardEmployeeContentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RewardEmployeeContentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RewardEmployeeContentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RewardEmployeeContentPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EmployeeComboBox;
    private javax.swing.JPanel RewardEmployeeForm;
    private javax.swing.JLabel RewardEmployeeLabel;
    private javax.swing.JTable RewardEmployeeTable;
    private javax.swing.JLabel RewardEmployeeTableLabel;
    private javax.swing.JLabel RewardIDLabel;
    private javax.swing.JTextField RewardIDTextField;
    private javax.swing.JLabel RewardNameEmployeeLabel;
    private javax.swing.JLabel RewardNameLabel;
    private javax.swing.JTextField RewardNameTextField;
    private javax.swing.JTextField RewardNumTextField;
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JSpinner moneySpinner;
    private javax.swing.JPanel rewardEmployeeFormContainer;
    private javax.swing.JPanel rewardEmployeeTableContainer;
    private javax.swing.JLabel rewardNumLabel;
    private javax.swing.JComboBox<String> typeRewardComboBox;
    private javax.swing.JLabel typeRewardNameLabel1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
